name: 'Post service metrics to Mackerel'
description: 'This is a simple action that posts service metrics to Mackerel (https://mackerel.io/).'
author: 'stefafafan'
inputs:
  api-key:
    required: true
    description: 'API Key value of Mackerel. Should be stored in GitHub Secrets.'
  service-name:
    required: true
    description: 'The Mackerel service name you want to post metrics to.'
  metric-name:
    required: true
    description: 'The Mackerel metric name you want to post.'
  metric-value:
    required: true
    description: 'The Mackerel metric value you want to post.'
  metric-time:
    required: false
    description: 'The time you want to post the metric. When not specified, the current time will be used.'
outputs:
  status:
    description: 'The status code of the POST request.'
runs:
  using: 'node16'
  main: 'dist/index.js'
